version: '3.8'

services:
  web:
    build:
      context: src/main/java
      dockerfile: Dockerfile
      # option to specify build args, if needed
      args:
        IMAGE_TAG: latest
        image: ${IMAGE_NAME}:${IMAGE_TAG}
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_MAIL_HOST=${SPRING_MAIL_HOST}
      - SPRING_MAIL_PORT=${SPRING_MAIL_PORT}
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
    ports:
      - "8081:8081"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge